export const langues = [
  "Plain Text", "Brainfuck", "C/C++", "C#", "CoffeeScript", "CSS", "Dart", "Django", "Elm", "Embedded Javascript",
  "Embedded Ruby", "Go", "Haskell", "Haskell (Literate)", "HXML", "ASP.NET", "HTML", "HTTP", "Pug", "Java",
  "Java Server Pages", "JavaScript", "JSON", "JSON-LD", "JSX", "Kotlin", "LESS", "Lua", "Markdown", "MariaDB SQL",
  "MS SQL", "MySQL", "Nginx", "Objective-C", "Pascal", "Perl", "PHP", "PowerShell", "Python", "R",
  "Ruby", "Sass", "Scala", "SCSS", "Shell", "SQL", "SQLite", "Stylus", "Swift", "LaTeX",
  "TypeScript", "TypeScript-JSX", "VB.NET", "VBScript", "Vue.js Component", "XML", "XQuery", "YAML",
]

export const modes = {
  "Plain Text": {mime: "text/plain", mode: "null"},
  "Brainfuck": {mime: "text/x-brainfuck", mode: "brainfuck"},
  "C/C++": {mime: "text/x-c++src", mode: "clike"},
  "C#": {mime: "text/x-csharp", mode: "clike"},
  "CoffeeScript": {mimes: ["application/vnd.coffeescript", "text/coffeescript", "text/x-coffeescript"], mode: "coffeescript"},
  "CSS": {mime: "text/css", mode: "css"},
  "Dart": {mimes: ["application/dart", "text/x-dart"], mode: "dart"},
  "Django": {mime: "text/x-django", mode: "django"},
  "Elm": {mime: "text/x-elm", mode: "elm"},
  "Embedded Javascript": {mime: "application/x-ejs", mode: "htmlembedded"},
  "Embedded Ruby": {mime: "application/x-erb", mode: "htmlembedded"},
  "Go": {mime: "text/x-go", mode: "go"},
  "Haskell": {mime: "text/x-haskell", mode: "haskell"},
  "Haskell (Literate)": {mime: "text/x-literate-haskell", mode: "haskell-literate"},
  "HXML": {mime: "text/x-hxml", mode: "haxe"},
  "ASP.NET": {mime: "application/x-aspx", mode: "htmlembedded"},
  "HTML": {mime: "text/html", mode: "htmlmixed"},
  "HTTP": {mime: "message/http", mode: "http"},
  "Pug": {mime: "text/x-pug", mode: "pug"},
  "Java": {mime: "text/x-java", mode: "clike"},
  "Java Server Pages": {mime: "application/x-jsp", mode: "htmlembedded"},
  "JavaScript": {mimes: ["text/javascript", "text/ecmascript", "application/javascript", "application/x-javascript", "application/ecmascript"],
  mode: "javascript"},
  "JSON": {mimes: ["application/json", "application/x-json"], mode: "javascript"},
  "JSON-LD": {mime: "application/ld+json", mode: "javascript"},
  "JSX": {mime: "text/jsx", mode: "jsx"},
  "Kotlin": {mime: "text/x-kotlin", mode: "clike"},
  "LESS": {mime: "text/x-less", mode: "css"},
  "Lua": {mime: "text/x-lua", mode: "lua"},
  "Markdown": {mime: "text/x-markdown", mode: "markdown"},
  "MariaDB SQL": {mime: "text/x-mariadb", mode: "sql"},
  "MS SQL": {mime: "text/x-mssql", mode: "sql"},
  "MySQL": {mime: "text/x-mysql", mode: "sql"},
  "Nginx": {mime: "text/x-nginx-conf", mode: "nginx"},
  "Objective-C": {mime: "text/x-objectivec", mode: "clike"},
  "Pascal": {mime: "text/x-pascal", mode: "pascal"},
  "Perl": {mime: "text/x-perl", mode: "perl"},
  "PHP": {mimes: ["text/x-php", "application/x-httpd-php", "application/x-httpd-php-open"], mode: "php"},
  "PowerShell": {mime: "application/x-powershell", mode: "powershell"},
  "Python": {mime: "text/x-python", mode: "python"},
  "R": {mime: "text/x-rsrc", mode: "r"},
  "Ruby": {mime: "text/x-ruby", mode: "ruby"},
  "Sass": {mime: "text/x-sass", mode: "sass"},
  "Scala": {mime: "text/x-scala", mode: "clike"},
  "SCSS": {mime: "text/x-scss", mode: "css"},
  "Shell": {mimes: ["text/x-sh", "application/x-sh"], mode: "shell"},
  "SQL": {mime: "text/x-sql", mode: "sql"},
  "SQLite": {mime: "text/x-sqlite", mode: "sql"},
  "Stylus": {mime: "text/x-styl", mode: "stylus"},
  "Swift": {mime: "text/x-swift", mode: "swift"},
  "LaTeX": {mime: "text/x-latex", mode: "stex"},
  "TypeScript": {mime: "application/typescript", mode: "javascript"},
  "TypeScript-JSX": {mime: "text/typescript-jsx", mode: "jsx"},
  "VB.NET": {mime: "text/x-vb", mode: "vb"},
  "VBScript": {mime: "text/vbscript", mode: "vbscript"},
  "Vue.js Component": {mimes: ["script/x-vue", "text/x-vue"], mode: "vue"},
  "XML": {mimes: ["application/xml", "text/xml"], mode: "xml"},
  "XQuery": {mime: "application/xquery", mode: "xquery"},
  "YAML": {mimes: ["text/x-yaml", "text/yaml"], mode: "yaml"},
};