export default {
  "Plain Text": "plain_text",
  "C/C++": "c_cpp",
  "C#": "csharp",
  "Coffee Script": "coffee",
  "CSS": "css",
  "Dart": "dart",
  "Django": "django",
  "Ejs": "ejs",
  "Elm": "elm",
  "Golang": "golang",
  "GraphQL": "graphqlschema",
  "HTML": "html",
  "Java": "java",
  "Javascript": "javascript",
  "JSON": "json",
  "JSP": "jsp",
  "JSX": "jsx",
  "Kotlin": "kotlin",
  "Latex": "latex",
  "LESS": "less",
  "Lua": "lua",
  "Markdown": "markdown",
  "Matlab": "matlab",
  "MySQL": "mysql",
  "Object-C": "objectivec",
  "Pascal": "pascal",
  "Perl": "perl",
  "PHP": "php",
  "Python": "python",
  "R": "r",
  "Ruby": "ruby",
  "SASS": "sass",
  "SCSS": "scss",
  "Scala": "scala",
  "SQL": "sql",
  "Stylus": "stylus",
  "SVG": "svg",
  "Swift": "swift",
  "TypeScript": "typescript",
  "VBScript": "vbscript",
  "XML": "xml",
  "YAML": "yaml"
}